=== user-friendly/bannerlord-perks/schema/perks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:mbb="http://www.example.org/perks/"
	targetNamespace="http://www.example.org/perks/"
	elementFormDefault="qualified"
>
	
	<!-- Base types. -->
	<xsd:simpleType name="DescriptionType">
		<xsd:union memberTypes="xsd:string" />
	</xsd:simpleType>
	
    <xsd:element name="Perks">
    	<xsd:complexType>
    		<xsd:sequence>
    			<xsd:element name="Perk" type="mbb:PerkType" minOccurs="1" maxOccurs="unbounded" />
    		</xsd:sequence>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="PerkType">
    	<xsd:sequence>
    		<xsd:element name="Property" type="mbb:PropertyType" minOccurs="1" maxOccurs="unbounded" />
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string" />
    	<xsd:attribute name="name" type="xsd:string" />
    	<xsd:attribute name="skill" type="xsd:string" />
    </xsd:complexType>
	
    <xsd:complexType name="PropertyType">
    	<xsd:sequence>
    		<xsd:element name="Target" type="xsd:string" />
    		<xsd:element name="Description" type="mbb:DescriptionType" />
    		<xsd:element name="Effects">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="Effect" type="mbb:EffectInstanceType" minOccurs="1" maxOccurs="unbounded"/>
    				</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="EffectInstanceType">
    	<xsd:attribute name="type" type="xsd:string" />
    	<xsd:attribute name="value" type="xsd:anySimpleType" />
    </xsd:complexType> 
</xsd:schema>

=== user-friendly/bannerlord-perks/perks.xml
<?xml version="1.0" encoding="UTF-8"?>

<Perks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:schemaLocation="http://www.example.org/perks/ schema/perks.xsd"
       xmlns="http://www.example.org/perks/"
>
	<Perk id="one_handed.basher" name="Basher" skill="one_handed" required="25">
		<Property>
			<Target>self</Target>
			<Description>+50% damage and longer stun durations with shield bashes.</Description>
			<Effects>
				<Effect type="effect.character.combat.damage.shield_bash" value="1.5" />
				<Effect type="effect.character.combat.stun.shield_bash" value="1.5" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>-4% damage taken by infantry while in shield wall formation</Description>
			<Effects>
				<Effect type="effect.character.combat.damage.resist.shield_wall" value="0.96" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.wrapped" name="Wrapped Handles" skill="one_handed" required="25">
		<Property>
			<Target>self</Target>
			<Description>+20% handling to one handed weapons.</Description>
			<Effects>
				<Effect type="effect.character.combat.handling.onehanded" value="1.2" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>+30 one handed skill to infantry troops in your formation.</Description>
			<Effects>
				<Effect type="effect.character.skill.onehanded" value="30" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.swift" name="Swift Strike" skill="one_handed" required="50">
		<Property>
			<Target>self</Target>
			<Description>+2% swing speed with one handed weapons</Description>
			<Effects>
				<Effect type="effect.character.combat.swing_speed.onehanded" value="1.02" />
			</Effects>
		</Property>
		
		<Property>
			<Target>manager</Target>
			<Description>+1 daily militia recruitment in the governed settlement.</Description>
			<Effects>
				<Effect type="effect.settlement.militia_recruitment" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.blunt" name="To Be Blunt" skill="one_handed" required="50">
		<Property>
			<Target>self</Target>
			<Description>+5% damage with one handed axes and maces.</Description>
			<Effects>
				<Effect type="effect.character.combat.damage.axe" value="1.05" />
				<Effect type="effect.character.combat.damage.mace" value="1.05" />
			</Effects>
		</Property>
		
		<Property>
			<Target>manager</Target>
			<Description>+0.5 daily security to governed settlement.</Description>
			<Effects>
				<Effect type="effect.TODO" value="0.5" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.cavalry" name="Cavalry" skill="one_handed" required="75">
		<Property>
			<Target>self</Target>
			<Description>+5% damage with one handed weapons while mounted.</Description>
			<Effects>
				<Effect type="effect.character.combat.damage.one_handed.mounted" value="1.05" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>+5% melee damage by cavalry troops in your formation.</Description>
			<Effects>
				<Effect type="effect.character.combat.damage.melee.mounted" value="1.05" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.bearer" name="Shield Bearer" skill="one_handed" required="75">
		<Property>
			<Target>self</Target>
			<Description>Remove movement speed penalty of wielding shields.</Description>
			<Effects>
				<Effect type="effect.character.combat.toggle.shield_penalty" value="false" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>+3% movement speed to infantry in your formation.</Description>
			<Effects>
				<Effect type="effect.character.combat.move_speed.infantry" value="1.03" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.duelist" name="Duelist" skill="one_handed" required="100">
		<Property>
			<Target>self</Target>
			<Description>+20% damage while wielding a one handed weapon without a shield.</Description>
			<Effects>
				<Effect type="effect.character.combat.damage.one_handed.no_shield" value="1.2" />
			</Effects>
		</Property>
		
		<Property>
			<Target>self</Target>
			<Description>Double the amount of renown gained from tournaments.</Description>
			<Effects>
				<Effect type="effect.character.renown.tournament.bonus" value="2" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.trainer" name="Trainer" skill="one_handed" required="100">
		<Property>
			<Target>self</Target>
			<Description>+2 hit points.</Description>
			<Effects>
				<Effect type="effect.character.combat.hp" value="2" />
			</Effects>
		</Property>
		
		<Property>
			<Target>party</Target>
			<Description>+5% experience to melee troops in your party after every battle.</Description>
			<Effects>
				<Effect type="effect.character.experience.bonus.post_battle.troop.melee.mult" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.catcher" name="Arrow Catcher" skill="one_handed" required="125">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed.shieldwall" name="Shieldwall" skill="one_handed" required="125">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed." name="" skill="one_handed" required="0">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed." name="" skill="one_handed" required="0">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed." name="" skill="one_handed" required="0">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed." name="" skill="one_handed" required="0">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed." name="" skill="one_handed" required="0">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed." name="" skill="one_handed" required="0">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed." name="" skill="one_handed" required="0">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>
	
	<Perk id="one_handed." name="" skill="one_handed" required="0">
		<Property>
			<Target>self</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
		
		<Property>
			<Target>officer</Target>
			<Description>Description</Description>
			<Effects>
				<Effect type="effect.TODO" value="1" />
			</Effects>
		</Property>
	</Perk>

</Perks>
